{% set version = "6.0.2" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: 6807947a09510dc31fa86f43595bf3a14017cd60bf633cc746d52141bfa6b149

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - tomli

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
