{% set version = "6.3.2" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: 03e2a7826086b91ef345ff18742ee9fc47a6839ccd517061ef8fa1976e652ce9

build:
  number: 1
  skip: true  # [py<37]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - tomli

test:
  requires:
    - pip
  imports:
    - coverage
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
