{% set version = "6.2" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: e2cad8093172b7d1595b4ad66f24270808658e11acf43a8f95b41276162eb5b8

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - tomli

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
